### ISSUE TITLE
Nex it.

### ISSUE THREAD

**Issue by gedw99** [johbar/text-extraction-service#4]
NATS Nex "could" run these once it's ready for prime time.  

It works no on desktops and Linux servers, so its not touch to get going.

https://github.com/synadia-io/nex/tree/main/examples/echoservice only runs native stuff.

https://github.com/synadia-io/nex/tree/main/examples/wasm/echofunction runs wasm,. but only a rust example so far.

https://github.com/syumai/workers can run the golang WASM on Cloudflare too, but I doubt PDFIUM wil work. Not sure..

**Comment by johbar** [comment]
I read the [annoucement of NEX](https://nats.io/blog/introducing_nex/) with quite some interest but concluded that I won't use it any time soon because it is a completely new runtime with no adoption atm.

For TES OCI containers are the easier way to go. As being said: NEX needs fully static binaries or Webassembly. Static linking of PDFium is difficult. WASM is killing performance.
